services:
  db:
    image: postgres:15-alpine
    container_name: thecapitalfeed-db
    restart: always
    environment:
      POSTGRES_USER: thecapitalfeed
      POSTGRES_PASSWORD: thecapitalfeed_pass_123
      POSTGRES_DB: thecapitalfeed
    ports:
      - '5436:5432'
    volumes:
      - thecapitalfeed_db_data:/var/lib/postgresql/data

volumes:
  thecapitalfeed_db_data:


